name: Deploy Laravel App to EC2 using SSM

on:
  push:
    branches:
      - main  # mainブランチへのpushをトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # AWS CLIの設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # SSMを使ってデプロイコマンドを実行
      - name: Deploy using SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Laravel Application" \
            --parameters '{"commands": [
              "set -eux",
              "cd /var/www/laravel-vue-echo",
              "git checkout main",
              "git pull origin main",
              "composer install --no-dev --optimize-autoloader",
              "php artisan migrate --force",
              "php artisan config:cache",
              "php artisan route:cache",
              "php artisan view:cache",
              "npm run install",
              "npm run build",
              "sudo systemctl reload nginx"
            ]}' \
            --output json \
            --query "Command.CommandId"

          echo "Command ID: $command_id"

          # command_idが空でないかを確認
          if [ -z "$command_id" ]; then
            echo "Error: Command ID is empty"
            exit 1
          fi

          # コマンド実行結果の取得
          result=$(aws ssm list-command-invocations \
            --command-id "$command_id" \
            --details \
            --output json)

          echo "Command result: $result"

      # デプロイ結果を表示
      - name: Display SSM Command Result
        run: |
          echo "Command executed successfully, check the result below:"
          echo "${{ steps.ssm_deploy.outputs.result }}"