name: Deploy Laravel App to EC2 using SSM

on:
  push:
    branches:
      - main  # mainブランチへのpushをトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # AWS CLIの設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # SSMを使ってデプロイコマンドを実行
      - name: Deploy using SSM
        run: |
          response=$(aws ssm send-command \
            --instance-ids ${{ secrets.INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Laravel Application" \
            --parameters '{"commands": [
              "set -eux",
              "export HOME=/home/ec2-user",
              "export COMPOSER_ALLOW_SUPERUSER=1",
              "git config --global --add safe.directory /var/www/laravel-vue-echo", 
              "cd /var/www/laravel-vue-echo",
              "git checkout main",
              "git pull origin main",
              "composer install --no-dev --optimize-autoloader",
              "php artisan migrate --force",
              "php artisan config:cache",
              "php artisan route:cache",
              "php artisan view:cache",
              "npm install",
              "npm run build",
              "sudo systemctl reload nginx"
          ]}' \
          --output json)

          echo "Response from send-command: $response"

          # CommandIdを取得
          command_id=$(echo $response | jq -r '.Command.CommandId')

          echo "Command ID: $command_id"

          # CommandIdが空でないか確認
          if [ -z "$command_id" ]; then
            echo "Error: Command ID is empty"
            exit 1
          fi

          # コマンド完了を待機
          aws ssm wait command-executed \
            --command-id "$command_id" \
            --instance-id ${{ secrets.INSTANCE_ID }}
          wait_status=$?

          if [ $wait_status -ne 0 ]; then
            echo "Waiter failed, fetching command details..."
            result=$(aws ssm get-command-invocation \
              --command-id "$command_id" \
              --instance-id ${{ secrets.INSTANCE_ID }} \
              --output json)

            echo "Command Result:"
            echo "$result"

            # エラー内容を表示
            stderr=$(echo "$result" | jq -r '.StandardErrorContent')
            echo "---- Standard Error ----"
            echo "$stderr"

            exit 1
          fi

          echo "Command execution completed successfully."

          # $command_id を後続ステップで使えるようエクスポート
          echo "COMMAND_ID=$command_id" >> $GITHUB_ENV

      # 実行結果を取得して表示
      - name: Fetch and Display SSM Command Result
        run: |
          echo "COMMAND_ID: $COMMAND_ID"
          echo "COMMAND_ID: $command_id"
          # 結果を取得1
          result=$(aws ssm get-command-invocation \
            --command-id "$command_id" \
            --instance-id ${{ secrets.INSTANCE_ID }} \
            --output json)

          # 出力を表示
          echo "Command Result:"
          echo "$result"

      # エラー詳細と標準出力を表示
      - name: Handle SSM Command Execution Result
        run: |
          # 結果を取得2
          result=$(aws ssm get-command-invocation \
            --command-id "$command_id" \
            --instance-id ${{ secrets.INSTANCE_ID }} \
            --output json)

          # ステータスを取得
          status=$(echo "$result" | jq -r '.Status')

          echo "Command Status: $status"

          # 標準出力とエラー出力を取得
          stdout=$(echo "$result" | jq -r '.StandardOutputContent')
          stderr=$(echo "$result" | jq -r '.StandardErrorContent')

          echo "---- Standard Output ----"
          echo "$stdout"

          echo "---- Standard Error ----"
          echo "$stderr"

          # ステータスがFailedの場合はエラーを返す
          if [ "$status" == "Failed" ]; then
            echo "Command execution failed."
            exit 1
          fi

          echo "Command executed successfully."
